#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.googymax3/.googymax3.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.googymax3/battery.profile /data/.googymax3/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.googymax3/balanced.profile /data/.googymax3/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.googymax3/performance.profile /data/.googymax3/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
