#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  
case "$hotplug" in

  0)
	mv /system/bin/mpdecision.googy /system/bin/mpdecision
	start mpdecision
        echo "0" > /cpufreq/enable_auto_hotplug
  ;; 
  1)
        echo "1" > /cpufreq/enable_auto_hotplug
        stop mpdecision
	mv /system/bin/mpdecision /system/bin/mpdecision.googy
  ;;
esac;

echo "Hotplug mechanism applied"

fi
fi
